# Generated by Django 6.1.1 on 2026-09-14 11:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('books', 'Books / Textbooks'), ('electronics', 'Electronics'), ('furniture', 'Furniture'), ('vehicles', 'Vehicles')], max_length=50)),
                ('transaction_type', models.CharField(choices=[('sell', 'Sell'), ('rent', 'Rent'), ('barter', 'Barter')], max_length=20)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('condition', models.CharField(choices=[('working', 'Working Condition'), ('broken', 'Broken / Needs Repair / E-Waste')], default='working', max_length=20)),
                ('photo_urls', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('active', 'Active'), ('sold', 'Sold'), ('rented', 'Rented'), ('removed', 'Removed')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BarterOffer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('offered_item_description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('offering_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_barters', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barter_offers', to='listings.listing')),
            ],
        ),
    ]
